# Generated by Django 5.1.4 on 2026-08-22 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_quantity_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('address_label', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('expected_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.scrapcategory')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantToMerchantSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfillment_method', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], db_index=True, max_length=20)),
                ('estimated_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING_FULFILLMENT', 'Pending Fulfillment'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING_FULFILLMENT', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('big_merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('bulk_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='merchant_network.bulkorder')),
                ('source_merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_source', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkOrderOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('big_merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_order_offers', to=settings.AUTH_USER_MODEL)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='merchant_network.bulkorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bulk_order', 'big_merchant'), name='unique_offer_per_bulk_order_and_merchant')],
            },
        ),
    ]
