# Generated by Django 5.1.4 on 2026-08-22 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('BROKEN', 'Broken'), ('WORKING', 'Working'), ('WORKING_BUT_OLD', 'Working but Old')], max_length=30)),
                ('photo_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('LISTED', 'Listed'), ('ACCEPTED', 'Accepted'), ('COLLECTED', 'Collected'), ('CLOSED', 'Closed')], db_index=True, default='LISTED', max_length=20)),
                ('accepted_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliances_accepted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appliance_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
