# Generated by Django 5.1.4 on 2026-08-25 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(max_length=150, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='appliances.appliancelisting')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appliance_bills_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
