# Generated by Django 5.1.4 on 2026-08-27 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_registration_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_owner_at', models.DateTimeField(auto_now_add=True)),
                ('branch_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_branch', to=settings.AUTH_USER_MODEL)),
                ('parent_merchant', models.ForeignKey(limit_choices_to={'role': 'MERCHANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='accounts_me_latitud_7f48c0_idx')],
            },
        ),
    ]
