# Generated by Django 5.1.4 on 2026-08-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merchantbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='language_preference',
            field=models.CharField(choices=[('EN', 'English'), ('TA', 'Tamil')], default='EN', max_length=5),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='voice_call_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='language_preference',
            field=models.CharField(choices=[('EN', 'English'), ('TA', 'Tamil')], default='EN', max_length=5),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='voice_call_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
