# Generated by Django 5.1.4 on 2026-08-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_companybill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybid',
            old_name='bid_amount',
            new_name='bid_rate_per_kg',
        ),
    ]
