# Generated by Django 5.1.4 on 2026-08-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_rename_bid_amount_companybid_bid_rate_per_kg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyBid',
            new_name='CompanyOffer',
        ),
        migrations.RenameField(
            model_name='companyoffer',
            old_name='bid_rate_per_kg',
            new_name='offer_amount',
        ),
        migrations.RenameField(
            model_name='companybill',
            old_name='company_bid',
            new_name='company_offer',
        ),
    ]
