# Generated by Django 5.1.4 on 2026-08-27 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20260827_1604'),
        ('pickups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyoffer',
            name='unique_bid_per_merchant',
        ),
        migrations.AlterField(
            model_name='companyoffer',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyoffer',
            name='pickup_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='pickups.pickuprequest'),
        ),
        migrations.AddConstraint(
            model_name='companyoffer',
            constraint=models.UniqueConstraint(fields=('pickup_request', 'merchant'), name='unique_offer_per_merchant'),
        ),
    ]
