# Generated by Django 5.1.4 on 2026-08-22 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('pickups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint_type', models.CharField(db_index=True, max_length=100)),
                ('evidence_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('resolution_outcome', models.CharField(blank=True, choices=[('AGAINST_MERCHANT', 'Against Merchant'), ('AGAINST_SOURCE', 'Against Source'), ('NO_FAULT', 'No Fault')], max_length=30, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_raised', to=settings.AUTH_USER_MODEL)),
                ('related_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pickups.bill')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.marketplacesale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
