# Generated by Django 5.1.4 on 2026-08-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
