# Generated by Django 5.1.4 on 2026-08-22 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('USER_PICKUP', 'User Pickup'), ('COMPANY_PICKUP', 'Company Pickup'), ('MERCHANT_TO_MERCHANT', 'Merchant to Merchant'), ('MARKETPLACE', 'Marketplace')], db_index=True, max_length=30, unique=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_rate_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('new_rate_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('changed_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='commission_rate_changes', to=settings.AUTH_USER_MODEL)),
                ('commission_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='settlements.commissionrate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
