# Generated by Django 5.1.4 on 2026-08-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_commissionrate_commissionratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettlementrecord',
            name='source_reference_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlementrecord',
            name='source_reference_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
