# Generated by Django 5.1.4 on 2026-08-29 13:19

from django.db import migrations


def seed_periodic_tasks(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # 1. Create 15-minute interval
    fifteen_min_schedule, _ = IntervalSchedule.objects.get_or_create(
        every=15,
        period='minutes',
    )

    # 2. Create daily 9 AM crontab
    daily_9am_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='9',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # 3. Create PeriodicTasks
    PeriodicTask.objects.update_or_create(
        name="Process expired leads",
        defaults={
            'task': 'pickups.tasks.process_expired_leads_task',
            'interval': fifteen_min_schedule,
            'enabled': True
        }
    )

    PeriodicTask.objects.update_or_create(
        name="Close ready bidding windows",
        defaults={
            'task': 'bidding.tasks.process_bidding_window_closures_task',
            'interval': fifteen_min_schedule,
            'enabled': True
        }
    )

    PeriodicTask.objects.update_or_create(
        name="Send offer window reminders",
        defaults={
            'task': 'bidding.tasks.send_offer_window_reminders_task',
            'interval': fifteen_min_schedule,
            'enabled': True
        }
    )

    PeriodicTask.objects.update_or_create(
        name="Send settlement reminders",
        defaults={
            'task': 'settlements.tasks.send_settlement_reminders_task',
            'crontab': daily_9am_schedule,
            'enabled': True
        }
    )


def remove_periodic_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    tasks_to_delete = [
        "Process expired leads",
        "Close ready bidding windows",
        "Send offer window reminders",
        "Send settlement reminders"
    ]
    PeriodicTask.objects.filter(name__in=tasks_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_marketplacesettlementrecord_source_reference_id_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RunPython(seed_periodic_tasks, reverse_code=remove_periodic_tasks),
    ]
