# Generated by Django 5.1.4 on 2026-08-22 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radius_used_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('BROADCASTED', 'Broadcasted'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REASSIGNED', 'Reassigned')], db_index=True, default='BROADCASTED', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('collection_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_copy_ref', models.CharField(max_length=100, unique=True)),
                ('merchant_copy_ref', models.CharField(max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_issued', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='pickups.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BROADCASTED', 'Broadcasted'), ('ACCEPTED', 'Accepted'), ('COLLECTED', 'Collected'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.scrapcategory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='pickup_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='pickups.pickuprequest'),
        ),
        migrations.CreateModel(
            name='RangeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_radius_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pickup_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_overrides', to='pickups.pickuprequest')),
                ('set_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['status', 'requested_at'], name='pickups_pic_status_ad8852_idx'),
        ),
    ]
