# Generated by Django 5.1.4 on 2026-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='offer_reminder_final_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='offer_reminder_halfway_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='offer_reminder_start_sent',
            field=models.BooleanField(default=False),
        ),
    ]
