# Generated by Django 5.1.4 on 2026-08-27 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(db_index=True, max_length=100)),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification'), ('VOICE_CALL', 'AI Voice Call')], db_index=True, max_length=20)),
                ('language_used', models.CharField(choices=[('EN', 'English'), ('TA', 'Tamil')], max_length=5)),
                ('message_content', models.TextField()),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('call_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'notification_type', 'created_at'], name='notificatio_account_4959bb_idx')],
            },
        ),
    ]
