# Generated by Django 5.1.4 on 2026-08-29 07:17

from django.db import migrations

def forwards_func(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    db_alias = schema_editor.connection.alias
    
    templates = [
        {
            "notification_type": "NEW_LEAD",
            "template_text": "A new pickup lead is available for {category} near {location}. Accept it before it expires."
        },
        {
            "notification_type": "OFFER_WINDOW_CLOSING",
            "template_text": "The sealed offer window for a {category} order closes in {time_remaining}. Submit your one-time offer now if you haven't already."
        },
        {
            "notification_type": "COMPLAINT_UPDATE",
            "template_text": "Your complaint #{complaint_id} ({complaint_type}) has been updated. Current status: {status}."
        },
        {
            "notification_type": "SETTLEMENT_REMINDER",
            "template_text": "You have {amount_owed} in pending commission settlement. Please complete payment to avoid service interruption."
        },
        {
            "notification_type": "REGISTRATION_APPROVED",
            "template_text": "Your ScrapConnect registration has been approved. You can now complete KYC verification from your profile page."
        },
        {
            "notification_type": "REGISTRATION_REJECTED",
            "template_text": "Your registration was not approved. Reason: {rejection_reason}. Please review and resubmit your details."
        },
        {
            "notification_type": "REGISTRATION_PERMANENTLY_REJECTED",
            "template_text": "Your registration has been permanently rejected after multiple unsuccessful attempts. Please contact support for further assistance."
        },
        {
            "notification_type": "KYC_VERIFIED",
            "template_text": "Your KYC verification is complete. You now have full access to ScrapConnect's features."
        },
        {
            "notification_type": "KYC_REJECTED",
            "template_text": "Your KYC verification was unsuccessful. Please check your submitted documents and try again."
        },
        {
            "notification_type": "BRANCH_CREATED",
            "template_text": "A new branch '{branch_name}' has been added to your merchant account."
        }
    ]
    
    for t in templates:
        NotificationTemplate.objects.using(db_alias).create(
            notification_type=t["notification_type"],
            template_text=t["template_text"],
            language="EN",
            is_active=True,
            updated_by=None
        )

def reverse_func(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    db_alias = schema_editor.connection.alias
    
    notification_types = [
        "NEW_LEAD", "OFFER_WINDOW_CLOSING", "COMPLAINT_UPDATE", 
        "SETTLEMENT_REMINDER", "REGISTRATION_APPROVED", 
        "REGISTRATION_REJECTED", "REGISTRATION_PERMANENTLY_REJECTED", 
        "KYC_VERIFIED", "KYC_REJECTED", "BRANCH_CREATED"
    ]
    
    NotificationTemplate.objects.using(db_alias).filter(
        notification_type__in=notification_types,
        language="EN"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtemplate'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
